security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            custom_authenticators:
                - App\Security\GoogleAuthenticator
                - App\Security\GithubAuthenticator
                - App\Security\DiscordAuthenticator
            logout:
                path: app_logout
                target: /

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/invitation/accept, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^//magic-link/use, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }        
        - { path: ^/*, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }